<?php

/**
 * Vue pour l'action TaskController::addAction()
 * Ajout d'une nouvelle tache
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzTask
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzTask/blob/master/view/dz-task/task/add.phtml
 */

?>

<h1>Ajout d'une tache</h1>
