<?php

/**
 * ProjectController::indexAction() view source
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzTask
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzProject/blob/master/view/dz-project/project/index.phtml
 */

?>

<h1>DzTask Module</h1>

<dl>
  <dt>Author</dt>
  <dd>Adrien Desfourneaux (aka Dieze51) &lt;dieze51@gmail.com&gt;</dd>
  
  <dt>Repository</dt>
  <dd>https://github.com/dieze/DzTask.git</dd>
</dl>
