<?php

/**
 * Vue pour l'action TaskController::showallAction()
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzTask
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzTask/blob/master/view/dz-task/task/showall.phtml
 */

?>

<h1>Tâches</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Période</th>
      <th>Etat</th>
    </tr>
  </thead>
  <tbody>
<?php
foreach ($tasks as $t) {
    ?>
    <tr>
      <td><?php echo $t->getDescription(); ?></td>
      <td><?php echo strftime("%d/%m/%Y", $t->getBeginDate()) . ' - ' . strftime("%d/%m/%Y", $t->getEndDate()); ?></td>
      <td><?php echo $t->getState()->getLabel(); ?></td>
    </tr>
    <?php
}
?>
  </tbody>
</table>