<?php

/**
 * Vue pour l'action TaskController::changestateAction()
 * Changement de l'état d'une tâche
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzTask
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link       https://github.com/dieze/DzTaskModule
 */

?>

<?php

$this->includeAssets();
$this->setHeadTitle("Changement d'état d'une tâche");

echo $this->renderTitle("Changement d'état d'une tâche");
echo $this->renderIconSelectJs();

$id  = $this->getVariable('id');

$action = $this->url('dztask/changestate',
	array(
		'id' => $id,
	)
);

?>

<div id="selectTaskState<?php echo $id; ?>"></div>

<form method="post" action="<?php echo $action; ?>" id="formTaskState<?php echo $id; ?>" class="changestateForm">
	<input type="hidden" name="taskState" id="taskState<?php echo $id; ?>" value=""/>
	<?php

    echo $this->renderRedirectSuccess();
    echo $this->renderRedirectFailure();
    echo $this->renderSubmit();

    ?>
</form>