<?php

/**
 * Vue pour l'action TaskController::listAction()
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzTaskModule
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link       https://github.com/dieze/DzTaskModule
 */

?>

<div id="calendar"></div>

<script type="text/javascript" src="/bower_components/jquery/jquery.js"></script>
<script type="text/javascript" src="/bower_components/underscore/underscore.js"></script>
<script type="text/javascript" src="/bower_components/bootstrap-calendar/js/calendar.js"></script>
<script type="text/javascript">
    var calendar = $('#calendar').calendar({
        events_source:
        [
            {
                "id": 293,
                "title": "Event 1",
                "url": "http://example.com",
                "class": "event-important",
                "start": 12039485678000, // Milliseconds
                "end": 1234576967000 // Milliseconds
            }
        ]
    });
</script>