<?php

/**
 * Vue pour le layout
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzTask
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link       https://github.com/dieze/DzTaskModule
 */

?>

<?php

$routeName   = $this->routeName();
$page = '';

switch ($routeName)
{
    case 'dztask':
        $page = 'info';
        break;

    case 'dztask/add':
        $page = 'add';
        break;

    case 'dztask/delete':
        $page = 'delete';
        break;

    case 'dztask/changestate':
        $page = 'changestate';
        break;

    case 'dztask/list':
        $page = 'list';
        break;
}

?>

<?php echo $this->doctype(); ?>
<?php //$page = $this->getPage(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('DzTaskModule')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
?>

<!-- Link -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'));
?>

<!-- Style -->
<?php echo $this->headStyle(); ?>

<!-- Script -->
<?php echo $this->headScript(); ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('dztask') ?>">DzTaskModule</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">

                        <li<?php if ($page == 'info') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dztask') ?>">Informations du module</a>
                        </li>

                        <li<?php if ($page == 'add') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dztask/add') ?>">Ajout d'une tâche</a>
                        </li>

                        <li<?php if ($page == 'changestate') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dztask/changestate', array('id' => '1')) ?>">Changement d'état d'une tâche</a>
                        </li>

                        <li<?php if ($page == 'list') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dztask/list') ?>">Listing des tâches</a>
                        </li>
                        
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
